# Generated by Django 5.1.6 on 2026-08-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='ig_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='video_url',
            field=models.TextField(blank=True, help_text='Hosted or source video URL'),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='profile_pic_url',
            field=models.TextField(blank=True),
        ),
    ]
